/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPrincipal;

import clases.Hash;
import clases.SqlUsuarios;
import clases.usuarios;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YANAC
 */
public class jPrincipalSFB extends javax.swing.JFrame {

    public static login frmlogin;
    private javax.swing.JDialog auxiliar;
    public Clip clip;
    public String ruta = "/music/";

    public jPrincipalSFB() {
        initComponents();
        sonido("NOMAN");
        ImageIcon icono = new ImageIcon("src/images/mundo rojo.jpg");
        setIconImage(icono.getImage());
        this.getContentPane().setBackground(Color.BLACK);

        setLocationRelativeTo(null);
        setSize(450, 600);
        setDefaultCloseOperation(jPrincipalSFB.EXIT_ON_CLOSE);

    }

    public void limpiar() {
        jTextFieldNombre.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldcontraseña.setText("");
        jPasswordFieldRepecontra.setText("");
    }

    public void sonido(String archivo) {
        try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav")));
            clip.start();

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jDialog1 = new javax.swing.JDialog();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        popupMenu1 = new java.awt.PopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroupsexo = new javax.swing.ButtonGroup();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanelDatos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanelContras = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPasswordFieldcontraseña = new javax.swing.JPasswordField();
        jPasswordFieldRepecontra = new javax.swing.JPasswordField();
        jButtonIniciar = new javax.swing.JButton();
        jButtonAcceder = new javax.swing.JButton();
        jButtonCrearNueva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarse = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 281, -1, -1));

        jPanelDatos.setBackground(new java.awt.Color(204, 0, 0));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelDatos.setForeground(new java.awt.Color(204, 0, 51));

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Crea un nombre de usuario: ");

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ingrese su correo:");

        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ingrese su nombre:");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDatosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 180));

        jPanelContras.setBackground(new java.awt.Color(204, 0, 0));
        jPanelContras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelContras.setForeground(new java.awt.Color(204, 0, 51));

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Crea una contraseña:");

        jLabel18.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Repita la contraseña:");

        jPasswordFieldcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldcontraseñaKeyPressed(evt);
            }
        });

        jPasswordFieldRepecontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldRepecontraKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContrasLayout = new javax.swing.GroupLayout(jPanelContras);
        jPanelContras.setLayout(jPanelContrasLayout);
        jPanelContrasLayout.setHorizontalGroup(
            jPanelContrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelContrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContrasLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldRepecontra))
                    .addGroup(jPanelContrasLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelContrasLayout.setVerticalGroup(
            jPanelContrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPasswordFieldcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jPasswordFieldRepecontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 340, 90));

        jButtonIniciar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonIniciar.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Iniciar sesión");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jButtonIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonIniciarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 110, -1));

        jButtonAcceder.setBackground(new java.awt.Color(204, 0, 0));
        jButtonAcceder.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jButtonAcceder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcceder.setText("Salir");
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        jButtonAcceder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAccederKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 500, 70, 30));

        jButtonCrearNueva.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCrearNueva.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jButtonCrearNueva.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearNueva.setText("Crear nueva cuenta");
        jButtonCrearNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearNuevaActionPerformed(evt);
            }
        });
        jButtonCrearNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCrearNuevaKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonCrearNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gif rojo.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 350, 160));

        jButtonRegistrarse.setBackground(new java.awt.Color(204, 0, 0));
        jButtonRegistrarse.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jButtonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        jButtonRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonRegistrarseKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed

        int resp = JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            dispose();
            this.setDefaultCloseOperation(jPrincipalSFB.EXIT_ON_CLOSE);
        } else {
            jTextFieldNombre.grabFocus();
        }


    }//GEN-LAST:event_jButtonAccederActionPerformed

    private void jButtonAccederKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAccederKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccederKeyPressed

    private void jButtonCrearNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearNuevaActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonCrearNuevaActionPerformed

    private void jButtonCrearNuevaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCrearNuevaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearNuevaKeyPressed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed

        //Para evitar que se habrán más ventanas 
        //LUego de presionar el botón
        if (frmlogin == null) {

            frmlogin = new login();
            frmlogin.setVisible(true);
            this.dispose();
        }
        
        clip.stop();

    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonIniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonIniciarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarKeyPressed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed

        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();

        String pass = new String(jPasswordFieldcontraseña.getPassword());
        String passC = new String(jPasswordFieldRepecontra.getPassword());

        if (jTextFieldUsuario.getText().equals("") || pass.equals("") || passC.equals("") || jTextFieldNombre.getText().equals("") || jTextFieldCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
        } else {

            if (pass.equals(passC)) {

                if (modSql.existeusuario(jTextFieldUsuario.getText()) == 0) {

                    if (modSql.esEmail(jTextFieldCorreo.getText())) {

                        String nuevoPass = Hash.sha1(pass);

                        mod.setUsuario(jTextFieldUsuario.getText());
                        mod.setPassword(nuevoPass);
                        mod.setNombre(jTextFieldNombre.getText());
                        mod.setCorreo(jTextFieldCorreo.getText());
                        mod.setTipo_usuario(1);

                        if (modSql.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                            limpiar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El email es incorrecto");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        }


    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jButtonRegistrarseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonRegistrarseKeyPressed
        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();

        String pass = new String(jPasswordFieldcontraseña.getPassword());
        String passC = new String(jPasswordFieldRepecontra.getPassword());

        if (jTextFieldUsuario.getText().equals("") || pass.equals("") || passC.equals("") || jTextFieldNombre.getText().equals("") || jTextFieldCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
        } else {

            if (pass.equals(passC)) {

                if (modSql.existeusuario(jTextFieldUsuario.getText()) == 0) {

                    if (modSql.esEmail(jTextFieldCorreo.getText())) {

                        String nuevoPass = Hash.sha1(pass);

                        mod.setUsuario(jTextFieldUsuario.getText());
                        mod.setPassword(nuevoPass);
                        mod.setNombre(jTextFieldNombre.getText());
                        mod.setCorreo(jTextFieldCorreo.getText());
                        mod.setTipo_usuario(1);

                        if (modSql.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado");
                            limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar");
                            limpiar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El email es incorrecto");
                        jTextFieldCorreo.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                    limpiar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                jPasswordFieldRepecontra.setText("");
            }
        }

    }//GEN-LAST:event_jButtonRegistrarseKeyPressed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jTextFieldUsuario.grabFocus();

        }
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jTextFieldCorreo.grabFocus();

        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jTextFieldCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyPressed
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jPasswordFieldcontraseña.grabFocus();

        }
    }//GEN-LAST:event_jTextFieldCorreoKeyPressed

    private void jPasswordFieldcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldcontraseñaKeyPressed
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jPasswordFieldRepecontra.grabFocus();

        }
    }//GEN-LAST:event_jPasswordFieldcontraseñaKeyPressed

    private void jPasswordFieldRepecontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRepecontraKeyPressed
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jButtonRegistrarse.grabFocus();

        }
    }//GEN-LAST:event_jPasswordFieldRepecontraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPrincipalSFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPrincipalSFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPrincipalSFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPrincipalSFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPrincipalSFB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupsexo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JButton jButtonCrearNueva;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelContras;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPasswordField jPasswordFieldRepecontra;
    private javax.swing.JPasswordField jPasswordFieldcontraseña;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

}
