/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormPrincipal;

import Juegos.PrincipalPPT;
import clases.Hash;
import clases.SqlUsuarios;
import clases.usuarios;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import menuOpciones.menuPrincipal;

/**
 *
 * @author Gerson AgY
 */
public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon("src/images/mundo rojo.jpg");
        setIconImage(icono.getImage());
        setTitle("Iniciar sesión");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jTextFieldIngreso = new javax.swing.JTextField();
        jButtonAcceder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldcontraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Usuario:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 111, -1, -1));

        jTextFieldIngreso.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jTextFieldIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresoActionPerformed(evt);
            }
        });
        jTextFieldIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIngresoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 108, 181, -1));

        jButtonAcceder.setBackground(new java.awt.Color(204, 0, 0));
        jButtonAcceder.setFont(new java.awt.Font("Palatino Linotype", 2, 14)); // NOI18N
        jButtonAcceder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        jButtonAcceder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAccederKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 30));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 160, -1, -1));

        jPasswordFieldcontraseña.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jPasswordFieldcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldcontraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 157, 181, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gif rojo.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresoActionPerformed

    private void jTextFieldIngresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIngresoKeyPressed
        // TODO add your handling code here:

        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jPasswordFieldcontraseña.grabFocus();
        }
    }//GEN-LAST:event_jTextFieldIngresoKeyPressed

    private void jPasswordFieldcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldcontraseñaKeyPressed
        // TODO add your handling code here:
        int cod = evt.getExtendedKeyCode();
        if (cod == KeyEvent.VK_ENTER) {
            jButtonAcceder.grabFocus();
        }
    }//GEN-LAST:event_jPasswordFieldcontraseñaKeyPressed


    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed

        SqlUsuarios modsql = new SqlUsuarios();
        usuarios mod = new usuarios();
        String pass = new String(jPasswordFieldcontraseña.getPassword());

        if (!jTextFieldIngreso.getText().equals("") && !jPasswordFieldcontraseña.getPassword().equals("")) {

            String nuevopass = Hash.sha1(pass);
            mod.setUsuario(jTextFieldIngreso.getText());
            mod.setPassword(nuevopass);

            if (modsql.login(mod)) {

                jPrincipalSFB.frmlogin = null;
                this.dispose(); //Para cerrar la ventana login

                menuPrincipal v = new menuPrincipal();
                v.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo iniciar sesión \nDatos incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Complete los espacios");
        }


    }//GEN-LAST:event_jButtonAccederActionPerformed

    private void jButtonAccederKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAccederKeyPressed
         SqlUsuarios modsql = new SqlUsuarios();
        usuarios mod = new usuarios();
        String pass = new String(jPasswordFieldcontraseña.getPassword());

        if (!jTextFieldIngreso.getText().equals("") && !jPasswordFieldcontraseña.getPassword().equals("")) {

            String nuevopass = Hash.sha1(pass);
            mod.setUsuario(jTextFieldIngreso.getText());
            mod.setPassword(nuevopass);

            if (modsql.login(mod)) {

                jPrincipalSFB.frmlogin = null;
                this.dispose(); //Para cerrar la ventana login

                menuPrincipal v = new menuPrincipal();
                v.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo iniciar sesión \nDatos incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Complete los espacios");
        }
    }//GEN-LAST:event_jButtonAccederKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        jPrincipalSFB.frmlogin = null;

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldcontraseña;
    private javax.swing.JTextField jTextFieldIngreso;
    // End of variables declaration//GEN-END:variables
}
